### ISSUE TITLE
allowScanningByMediaScanner deprecated

### ISSUE THREAD

**Issue by AstaClover** [snajdovski/TikTokFetch-No-Watermark#1]
![Screenshot (1420)](https://user-images.githubusercontent.com/45400747/83364014-95349e00-a3d0-11ea-95cd-5f82c17dda98.png)

how to fix this?

**Comment by AstaClover** [comment]
downloaded video cant be see in any file except on com./data/

also cant found it on gallery

**Comment by snajdovski** [comment]
I will need to rewrite this part, as is deprecated, Android 10 Changed a lot of things with how storage is managed, could you try to install file manager and see if there is a video saved in a folder called TikFetch?

**Comment by snajdovski** [comment]
You can delete the deprecated parts that are crossed as they are probably not needed, the app was, for the gallery part you can do the follwing:
```
    public void downloader(String str) {
        new Handler(Looper.getMainLooper()).post(() -> {
            Context applicationContext = MainActivity.this.getApplicationContext();
            Toast.makeText(applicationContext, "" + MainActivity.this.getString(R.string.download_started), Toast.LENGTH_LONG).show();
        });
        String string = getString(R.string.downloading);
        DownloadManager.Request request = new DownloadManager.Request(Uri.parse(withoutWatermark(str)));
        request.setAllowedNetworkTypes(3);
        request.setAllowedOverRoaming(true);
        request.setTitle(getString(R.string.app_name));
        request.setDescription(string);
        request.setNotificationVisibility(1);
        request.setDestinationInExternalFilesDir(this, Environment.DIRECTORY_DCIM, ("tiktok__" + System.currentTimeMillis()) + "." + "mp4");

        ((DownloadManager) getSystemService(DOWNLOAD_SERVICE)).enqueue(request);
    }
```

**Comment by AstaClover** [comment]
the video isnt show on file manager also on gallery.. its show on apps data ill try the code

**Comment by snajdovski** [comment]
Wait for a commit, I will fix this issue soon. As soon as I get home.
