### ISSUE TITLE
Still same

### ISSUE THREAD

**Issue by AstaClover** [snajdovski/TikTokFetch-No-Watermark#4]
New merge also cant see the downloaded video on Gallery, no file named TiktokFetch was found to

**Comment by snajdovski** [comment]
> New merge also cant see the downloaded video on Gallery, no file named TiktokFetch was found to

Dude, you have the code replace the snippet that I mentioned with the Uri of your gallery and it will work I have more important issues than TikTok downloader, when I have more free time I will look into it, I don't see any problem the app downloads the videos to a folder you know just copy-paste to the place you want.

**Comment by jaykeerti** [comment]
@AstaClover i think it is downloading in the default destination of the app directory. you can use the follwoing code to show in public directory

`request.setDestinationInExternalPublicDir("TikTokDownloads/Videos",("tiktok__" + System.currentTimeMillis()) + "." + "mp4");`

**Comment by snajdovski** [comment]
@jaykeerti It will do the same issue you need to change it everything after the dot (I think).
