### ISSUE TITLE
0 Byte

### ISSUE THREAD

**Issue by sushantj651** [snajdovski/TikTokFetch-No-Watermark#5]
Video is downloaded but it's size is 0 byte and can't play video

**Comment by jaykeerti** [comment]
Can you share the code where you are writing the file?

**Comment by sushantj651** [comment]
`public void saveVideo(final String str) {
        new Thread(){
            @Override
            public void run() {
                try {
                    String playURL = "";

                    final Document document = Jsoup.connect(str)
                            .userAgent("Mozilla/5.0 (Linux; U; Android 4.0.2; en-us; Galaxy Nexus Build/ICL53F) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30")
                            .get();

                    for (Element element : document.select("script")) {
                        final String data = element.data();
                        if (data.contains("videoData")) {
                            final String substring = data.substring(data.lastIndexOf("urls"));
                            final String substring2 = substring.substring(substring.indexOf("[") + 1);
                            final String substring3 = substring2.substring(0, substring2.indexOf("]"));
                            playURL = substring3.substring(1, substring3.length() - 1);
                        }
                    }

                    downloader(playURL);
                } catch (final Exception e) {
                    //Log.e("tiktok", "", e);
                    Toast.makeText(getContext(),"saveVideo toast",Toast.LENGTH_LONG).show();
                }
            }
        }.start();
    }

    public void downloader(final String str) {
//        new Handler(Looper.getMainLooper()).post(() ->
//                Toast.makeText(getContext(), "Download Started", Toast.LENGTH_SHORT).show());
        new Handler(Looper.getMainLooper()).post(
                new Runnable() {
                    @Override
                    public void run() {
                        Toast.makeText(getContext(), "Download Started", Toast.LENGTH_SHORT).show();
                    }
                }
        );

        final DownloadManager.Request request = new DownloadManager.Request(Uri.parse(withoutWatermark(str)));
        request.setAllowedNetworkTypes(DownloadManager.Request.NETWORK_MOBILE | DownloadManager.Request.NETWORK_WIFI);
        request.setAllowedOverRoaming(true);
        request.setTitle(getString(R.string.app_name));
//        request.setDescription(getString(R.string.downloading));
        request.setDescription("Downloading...");
        request.setVisibleInDownloadsUi(true);
        request.allowScanningByMediaScanner();
        request.setNotificationVisibility(DownloadManager.Request.VISIBILITY_VISIBLE_NOTIFY_COMPLETED);
        request.setDestinationInExternalFilesDir(getContext(), "/TikFetch", ("tiktok__" + System.currentTimeMillis()) + "." + "mp4");

        downloadManager.enqueue(request);
    }

    public String withoutWatermark(final String url) {
        try {
            final HttpURLConnection httpURLConnection = (HttpURLConnection) new URL(url).openConnection();
            httpURLConnection.connect();
            if (httpURLConnection.getResponseCode() == HttpURLConnection.HTTP_OK) {
                final BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(httpURLConnection.getInputStream()));
                final StringBuilder stringBuffer = new StringBuilder();

                String readLine;
                while ((readLine = bufferedReader.readLine()) != null) {
                    stringBuffer.append(readLine);

                    if (stringBuffer.toString().contains("vid:")) {
                        try {
                            if (stringBuffer.substring(stringBuffer.indexOf("vid:")).substring(0, 4).equals("vid:")) {
                                final String substring = stringBuffer.substring(stringBuffer.indexOf("vid:"));
                                final String trim = substring.substring(4, substring.indexOf("%"))
                                        .replaceAll("[^A-Za-z0-9]", "").trim();
                                return "https://api2.musical.ly/aweme/v1/playwm/?video_id=" + trim;
                            }
                        } catch (final Exception e) {
                            Log.e("tiktok", "", e);
                        }
                    }
                }
            }

        } catch (final Exception e) {
            Log.e("tiktok", "", e);
        }

        return "";
    }`

> 
> 
> Can you share the code where you are writing the file?



> 
> 
> Can you share the code where you are writing the file?

**Comment by sushantj651** [comment]
```
public void saveVideo(final String str) {
        new Thread(){
            @Override
            public void run() {
                try {
                    String playURL = "";

                    final Document document = Jsoup.connect(str)
                            .userAgent("Mozilla/5.0 (Linux; U; Android 4.0.2; en-us; Galaxy Nexus Build/ICL53F) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30")
                            .get();

                    for (Element element : document.select("script")) {
                        final String data = element.data();
                        if (data.contains("videoData")) {
                            final String substring = data.substring(data.lastIndexOf("urls"));
                            final String substring2 = substring.substring(substring.indexOf("[") + 1);
                            final String substring3 = substring2.substring(0, substring2.indexOf("]"));
                            playURL = substring3.substring(1, substring3.length() - 1);
                        }
                    }

                    downloader(playURL);
                } catch (final Exception e) {
                    //Log.e("tiktok", "", e);
                    Toast.makeText(getContext(),"saveVideo toast",Toast.LENGTH_LONG).show();
                }
            }
        }.start();
    }

    public void downloader(final String str) {
        new Handler(Looper.getMainLooper()).post(
                new Runnable() {
                    @Override
                    public void run() {
                        Toast.makeText(getContext(), "Download Started", Toast.LENGTH_SHORT).show();
                    }
                }
        );

        final DownloadManager.Request request = new DownloadManager.Request(Uri.parse(withoutWatermark(str)));
        request.setAllowedNetworkTypes(DownloadManager.Request.NETWORK_MOBILE | DownloadManager.Request.NETWORK_WIFI);
        request.setAllowedOverRoaming(true);
        request.setTitle(getString(R.string.app_name));
        request.setDescription("Downloading...");
        request.setVisibleInDownloadsUi(true);
        request.allowScanningByMediaScanner();
        request.setNotificationVisibility(DownloadManager.Request.VISIBILITY_VISIBLE_NOTIFY_COMPLETED);
        request.setDestinationInExternalFilesDir(getContext(), "/TikFetch", ("tiktok__" + System.currentTimeMillis()) + "." + "mp4");

        downloadManager.enqueue(request);
    }

    public String withoutWatermark(final String url) {
        try {
            final HttpURLConnection httpURLConnection = (HttpURLConnection) new URL(url).openConnection();
            httpURLConnection.connect();
            if (httpURLConnection.getResponseCode() == HttpURLConnection.HTTP_OK) {
                final BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(httpURLConnection.getInputStream()));
                final StringBuilder stringBuffer = new StringBuilder();

                String readLine;
                while ((readLine = bufferedReader.readLine()) != null) {
                    stringBuffer.append(readLine);

                    if (stringBuffer.toString().contains("vid:")) {
                        try {
                            if (stringBuffer.substring(stringBuffer.indexOf("vid:")).substring(0, 4).equals("vid:")) {
                                final String substring = stringBuffer.substring(stringBuffer.indexOf("vid:"));
                                final String trim = substring.substring(4, substring.indexOf("%"))
                                        .replaceAll("[^A-Za-z0-9]", "").trim();
                                return "https://api2.musical.ly/aweme/v1/playwm/?video_id=" + trim;
                            }
                        } catch (final Exception e) {
                            Log.e("tiktok", "", e);
                        }
                    }
                }
            }

        } catch (final Exception e) {
            Log.e("tiktok", "", e);
        }

        return "";
    }
```

**Comment by yrickwong** [comment]
0Byte , the project yesterday is work  ,but   is  not working now ,download file is 0 byte

**Comment by yrickwong** [comment]
https://api2.musical.ly/aweme/v1/playwm/?video_id    this api can not access anymore

**Comment by sushantj651** [comment]
Is there any alternative of this?

**Comment by jaykeerti** [comment]
> Is there any alternative of this?

Nothing that i know of

**Comment by jaykeerti** [comment]
> https://api2.musical.ly/aweme/v1/playwm/?video_id this api can not access anymore

What error do you get here?

**Comment by snajdovski** [comment]
Well that's the end here, if I find a way again to download I will update the app.

**Comment by Jetereting** [comment]
Mark to notice me.

**Comment by Inzilkin** [comment]
Yep, me too please

**Comment by snajdovski** [comment]
Does any of you know what does MIT license even mean,or you are just here to leech the app and post on play store?
The App is made just for educational purposes I don't think I will fix something ASAP just for some leechers to make money out of it. 
Good Day.
BTW for the open source community you can pull a request if someone finds a way to fix it. thanks.

**Comment by snajdovski** [comment]
Fixed!

**Comment by nhacvanbien** [comment]
after downloading the files, it can not be opened

**Comment by snajdovski** [comment]
@nhacvanbien Probably tiktok changed their API again
